"""Render SCREEN_REPORT.md from BarResult rows."""

from __future__ import annotations

from pathlib import Path
from typing import List, Sequence

import numpy as np

from .bars import (
    BEYOND_RATE_MAX_ABS_SPEARMAN,
    STABILITY_MAX_MEDIAN_CV,
    STABILITY_MIN_SPEARMAN,
    TREATMENT_MIN_ABS_COHEN_D,
    BarResult,
)


def render_screen_report(
    results: Sequence[BarResult],
    *,
    recording: str,
    injury_label: str,
    injury_start_s: float,
    injury_end_s: float,
    baseline_regions: Sequence[int],
    during_regions: Sequence[int],
    post_regions: Sequence[int],
) -> str:
    metrics: List[str] = []
    for r in results:
        if r.metric not in metrics:
            metrics.append(r.metric)

    lines: List[str] = [
        f"# Screening report — {recording}",
        "",
        (
            f"Generated by `python -m mea_metrics.screen`. Injury: **{injury_label}** "
            f"[{injury_start_s:.0f}, {injury_end_s:.0f}] s."
        ),
        "",
        "## Region split",
        "",
        f"- Baseline (pre): `{list(baseline_regions)}`",
        f"- During injury: `{list(during_regions)}`",
        f"- Post: `{list(post_regions)}`",
        "",
        "## Thresholds (frozen on SMJM 2026-09-22)",
        "",
        (
            f"- Baseline stability: split-half Spearman ≥ **{STABILITY_MIN_SPEARMAN}** "
            f"(soft diagnostic: median unit CV ≤ {STABILITY_MAX_MEDIAN_CV})"
        ),
        (
            f"- Beyond rate: |Spearman(metric, rate_hz)| < **{BEYOND_RATE_MAX_ABS_SPEARMAN}** "
            "(rate_hz itself SKIP)"
        ),
        (
            f"- Treatment response: |Cohen's d| (post vs baseline) ≥ **{TREATMENT_MIN_ABS_COHEN_D}** "
            "(*n=1 culture, no holdout*)"
        ),
        "- Interpretability: registered plain-language blurb (A v1 auto-pass if present)",
        "",
        "Failed bars stay listed as **FAIL** (lab rule).",
        "",
        "## Results",
        "",
        "| metric | baseline_stability | beyond_rate | treatment_response | interpretability |",
        "|---|---|---|---|---|",
    ]

    by = {(r.metric, r.bar): r for r in results}
    bars = ("baseline_stability", "beyond_rate", "treatment_response", "interpretability")
    for m in metrics:
        cells = []
        for b in bars:
            r = by.get((m, b))
            if r is None:
                cells.append("—")
            else:
                cells.append(f"**{r.status}**" if r.status == "FAIL" else r.status)
        lines.append(f"| `{m}` | " + " | ".join(cells) + " |")

    lines.extend(["", "## Detail notes", ""])
    for m in metrics:
        lines.append(f"### `{m}`")
        lines.append("")
        for b in bars:
            r = by.get((m, b))
            if r is None:
                continue
            score = "nan" if not np.isfinite(r.score) else f"{r.score:.4g}"
            lines.append(f"- **{b}**: {r.status} (score={score}; {r.threshold}) — {r.note}")
        lines.append("")
    return "\n".join(lines)


def write_screen_report(text: str, path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path
